# https://github.com/habx/devops-repo-shared-configs/blob/dev/github-settings/go-service.yml
# 2022-03-17
# last_update: 2022-04-07
_extends: devops-repo-shared-configs:github-settings/go-service.yml
